site_name: Docker AI Assistant
site_url: https://smeekpers.github.io/docker_ai_assistant/
repo_url: https://github.com/smeekpers/docker_ai_assistant
repo_name: docker_ai_assistant

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - toc

copyright: Copyright &copy; 2026 Docker AI Assistant Contributors

nav:
  - Home: index.md

  - Architecture:
      - Overview: architecture.md

  - Setup:
      - Deployment: setup/deployment.md
      - Docker:
          - Rebuild Run Book: setup/docker_rebuild_run_book.md
          - Docker Setup: setup/docker.md
      - GitHub: setup/github.md
      - Zensical Rebuild and Start: setup/zensical_build.md

  - Testing:
      - Testing Guide: testing.md

  - Troubleshooting:
      - Zensical 404 Error: troubleshooting/Zensical 404 error.md
      - Docker Errors: troubleshooting/docker-errors.md
      - FastAPI Errors: troubleshooting/fastapi-errors.md
      - Git Errors: troubleshooting/git-errors.md
      - Pre-commit Errors:
          - Black no files to check: troubleshooting/Errors/black_no files_to_check.md
          - Stashed changes conflicted with hook: troubleshooting/Errors/Stashed changes conflicted with hook.md
          - Unstaged Files Detected: troubleshooting/Errors/Unstaged Files Detected.md
